### ISSUE TITLE
running ChromHMM LearnModel on a headless node (no X11)

### ISSUE THREAD

**Issue by avilella** [jernst98/ChromHMM#1]
Hi,

Is it possible to run ChromHMM LearnModel on a Linux node with no X11?

I am running it like below and get the following error:
```
java -mx1600M -jar /bi/home/rocks-av/ChromHMM/ChromHMM.jar LearnModel -p 0 -nobrowser /bi/group/cegx/CEGX_Run434/CEGX_Run434-12345678/inputbams/BINARIES /bi/group/cegx/CEGX_Run434/CEGX_Run434-12345678/inputbams/CHROMHMM 2 hg38                                                                                                                                                                                            Using 8 threads for Baum-Welch training
Writing to file /bi/group/cegx/CEGX_Run434/CEGX_Run434-12345678/inputbams/CHROMHMM/transitions_2.txt
Writing to file /bi/group/cegx/CEGX_Run434/CEGX_Run434-12345678/inputbams/CHROMHMM/emissions_2.txt
connect localhost port 6044: Connection refused
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:10.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at org.tc33.jheatchart.HeatChart.measureComponents(HeatChart.java:1406)
        at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1301)
        at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1354)
        at edu.mit.compbio.ChromHMM.Util.printImageToSVG(Util.java:140)
        at edu.mit.compbio.ChromHMM.ChromHMM.printEmissionImage(ChromHMM.java:1215)
        at edu.mit.compbio.ChromHMM.ChromHMM.trainParametersParallel(ChromHMM.java:4817)
        at edu.mit.compbio.ChromHMM.ChromHMM.buildModel(ChromHMM.java:816)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:6412)
```

**Comment by ernstlab** [comment]
To generate ChromHMM's parameter images the system needs to have the necessary support for that.
I could consider adding the option for ChromHMM not to generate image output in a future version.

-Jason

**Comment by balwierz** [comment]
Meanwhile, is there a way to circumvent it? I.e. that ChromHMM skips launching a web browser?

**Comment by avilella** [comment]
I managed to get it to work with:

unset DISPLAY && java -mx1600M -jar $chromhmm LearnModel -s 1 -p $threads
-nobrowser $binariesdir $modelsdir $num_states $assembly

**Comment by jernst98** [comment]
I've added a -noimage flag in version 1.14 of ChromHMM which suppresses the printing of image out.

-Jason

**Comment by JohnMCMa** [comment]
I would like to add another solution here. I tested running `LearnModel` using Sun Java's own headless mode. By adding the flag `-Djava.awt.headless=true` to the java invocation, ChromHMM generates all figures and did not throw any errors, other than a warning of the inability to open a browser.
