### ISSUE TITLE
Coordinates in CpGIsland.MSU7.bed not assigned to any state

### ISSUE THREAD

**Issue by mforoozani1** [jernst98/ChromHMM#13]
I run OverlapEnrichment for my data, but I got this error: 
Exception in thread "main" java.lang.IllegalArgumentException: Coordinates in CpGIsland.MSU7.bed not assigned to any state
	at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:1065)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:10015)
I was wondering how I can fix this error. I made CpGislands file by running EMBOSS. 
Thanks
Maryam

**Comment by jernst98** [comment]
Hi Maryam,

Can you check whether your chromosome naming scheme for the input chromatin data to ChromHMM matches what you are using for the CpG islands?  In some cases when I have seen this error people include the 'chr' as part of the chromosome name in one set of files, but not the other.

Thanks,
-Jason

**Comment by mforoozani1** [comment]
oh, Thanks! That is true, my input has Chr but CpGislans has chr! many thanks.

**Comment by mforoozani1** [comment]
now I got another error:
xception in thread "main" java.lang.ArrayIndexOutOfBoundsException: -4
	at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:935)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:10015)

**Comment by jernst98** [comment]
This suggest to me there are negative coordinates in one of your external files for enrichment analysis.
Can you check whether that is the case?

-Jason
