### ISSUE TITLE
bam not found by BinarizeBam command

### ISSUE THREAD

**Issue by El-Castor** [jernst98/ChromHMM#21]
Hi I'm trying to use chromHMM on my Chipseq data. But I got an error trying to binarize my bam file with the BinarizeBam command. Please can you help to fix this issue. 

here you have my cellMarkFile.tab : 

> leaf	H3K9ac	trimmed_11375_Melon_MBDL36_ACTTGA_L00345_001_filtered.bam    
leaf	H3K27me3	trimmed_11376_Melon_MBDL37_GATCAG_L00345_001_filtered.bam    
leaf	meDip	trimmed_M_15_A781_MBDL18_P-16_ArabidopsisandMelon_CGATGT_L008_001_filtered.bam    

here you have the executed command : 

```bash
$java -mx1600M -jar "$classPath/ChromHMM.jar" BinarizeBam -b $binSizeOption -t $outputSignalDir $pairedOption $chromSizePath $bamFileDir $cellMarkFileTablePath $outputBinaryDir
```

Here you have the java error : 

> Exception in thread "main" htsjdk.samtools.util.RuntimeIOException: java.io.FileNotFoundException: data/trimmed_11375_Melon_MBDL36_ACTTGA_L00345_001_filtered.bam  (Aucun fichier ou dossier de ce type)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:171)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:165)
	at htsjdk.samtools.util.Lazy.get(Lazy.java:24)
	at htsjdk.samtools.FileInputResource.asUnbufferedSeekableStream(SamInputResource.java:194)
	at htsjdk.samtools.FileInputResource.asUnbufferedInputStream(SamInputResource.java:199)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:245)
	at htsjdk.samtools.SamReaderFactory$SamReaderFactoryImpl.open(SamReaderFactory.java:133)
	at edu.mit.compbio.ChromHMM.Preprocessing.loadGrid(Preprocessing.java:195)
	at edu.mit.compbio.ChromHMM.Preprocessing.makeBinaryDataFromBed(Preprocessing.java:1016)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:12483)
Caused by: java.io.FileNotFoundException: data/trimmed_11375_Melon_MBDL36_ACTTGA_L00345_001_filtered.bam  (Aucun fichier ou dossier de ce type)
	at java.io.RandomAccessFile.open(Native Method)
	at java.io.RandomAccessFile.<init>(RandomAccessFile.java:241)
	at htsjdk.samtools.seekablestream.SeekableFileStream.<init>(SeekableFileStream.java:47)
	at htsjdk.samtools.FileInputResource$1.make(SamInputResource.java:169)
	... 9 more

More over here you have the my environment that I used : 

-  java==1.7 (tested also with java8 and java11 but failed)
-  chromHMM==1.19 (also tried with chromHMM==1.15 but failed)

**Comment by El-Castor** [comment]
For now, I'm converting my bam file to bed file to try using BinarizeBed command and see if it will succeed.

**Comment by jernst98** [comment]
Are you sure you have a file named 'trimmed_11375_Melon_MBDL36_ACTTGA_L00345_001_filtered.bam'
in a directory named 'data' in the directory from which you are executing ChromHMM?

**Comment by El-Castor** [comment]
yes i checked for that:

```bash
$ ls data/
cellMarkFileTable.tab
trimmed_11375_Melon_MBDL36_ACTTGA_L00345_001_filtered.bam
...
```

**Comment by jernst98** [comment]
Have you gotten BinarizeBam or BinarizeBed to work with any data on your computer?

You may also want to check that there is no trailing spaces in cellMarkFile.tab after the file names.

**Comment by El-Castor** [comment]
You were right, I didn't pay enough attention to the trailing space after the bam filename.
Now BinarizeBam run without error.

Thank you so much!
