### ISSUE TITLE
chromHMM overlap enrichments error for input string: "E"

### ISSUE THREAD

**Issue by fionaandcake11** [jernst98/ChromHMM#24]
I get the following error when I try to use OverlapEnrichments on a model with 18 states. 

Computing Enrichments...
Exception in thread "main" java.lang.NumberFormatException: For input string: "E"
	at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
	at java.base/java.lang.Integer.parseInt(Integer.java:652)
	at java.base/java.lang.Integer.parseInt(Integer.java:770)
	at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:691)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13336)**

The problem is apparently the first row of the third column because the input string value in the command changes to whatever I put in the model file in that position unless the value I change it to is an integer, in which case it gives me this error: 

Computing Enrichments...
Exception in thread "main" java.lang.IllegalArgumentException: Binsize of 200 does not agree with input segment 18	11	200	-5142465.9198876005	200
	at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:694)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13336)

Is there something wrong with my segmentation file? It's labeled as model_18.txt from the original LearnModel ouput, and I thought the E was just meant to show that the states were ordered based on emission.

Thank you!

**Comment by jernst98** [comment]
It looks like you are giving as input the model file to OverlapEnrichment. You should instead be giving the segmentation file.
