### ISSUE TITLE
error in binarizeSignal

### ISSUE THREAD

**Issue by KailiBio** [jernst98/ChromHMM#26]
Hi! I am running ChromHMM binarizeSignal for a signal matrix, with comment "java -Xmx16G -jar ChromHMM.jar BinarizeSignal signalFile binaryFile", and occationally get an error (shown below)

Exception in thread "main" java.util.NoSuchElementException
	at java.base/java.util.StringTokenizer.nextToken(StringTokenizer.java:349)
	at edu.mit.compbio.ChromHMM.Preprocessing.makeBinaryDataFromSignalUniform(Preprocessing.java:3207)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13197)

Do you have any suggestions?

**Comment by jernst98** [comment]
This means there is a line in your signal data with fewer tab-delimited values than the number of marks.
I'll try to add a more informative error message for this in the next version of ChromHMM

-Jason
