### ISSUE TITLE
overlap enrichment issue

### ISSUE THREAD

**Issue by AicuiZhang** [jernst98/ChromHMM#32]
Hi! dear developer.

When I ran overlap enrichemnt, I met a problem. I searched in the issues websites, but no one had similar question.

my command is "java -jar /xtdisk/renjie_group/chixu/chromHMM/ChromHMM.jar OverlapEnrichment -signal /LearnModel/fetal-liver_13_segments.bed /chromHMM/inputcoorddir/ /chromHMM/OverlapEnrichment-signal/OverlapEnrichment-family"

and the error is 
Computing Enrichments...
Exception in thread "main" java.lang.NumberFormatException: For input string: "AluSp"
        at sun.misc.FloatingDecimal.readJavaFormatString(FloatingDecimal.java:2043)
        at sun.misc.FloatingDecimal.parseDouble(FloatingDecimal.java:110)
        at java.lang.Double.parseDouble(Double.java:538)
        at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:1097)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13926)

looking forward your suggestions. and thank you

**Comment by jernst98** [comment]
You have the '-signal' flag, but your fourth column does not contain numerical signal values.
I suggest removing the signal flag. Note if you want to compute different enrichments depending
on the contents of the fourth column, then you should partition the bed file into separate bed files
based on the content of the fourth column.

**Comment by AicuiZhang** [comment]
thank you very much! It helped a lot.
