### ISSUE TITLE
Exception` in thread "main" java.util.zip.ZipException: invalid distance too far back

### ISSUE THREAD

**Issue by Simple53** [jernst98/ChromHMM#43]
Dear all,
I was using the latest version of ChromHMM. But I could not get a `.html` file using LearnModel and got an err when  like this:
```
Exception` in thread "main" java.util.zip.ZipException: invalid distance too far back
	at java.base/java.util.zip.InflaterInputStream.read(InflaterInputStream.java:165)
	at java.base/java.util.zip.GZIPInputStream.read(GZIPInputStream.java:118)
	at java.base/sun.nio.cs.StreamDecoder.readBytes(StreamDecoder.java:284)
	at java.base/sun.nio.cs.StreamDecoder.implRead(StreamDecoder.java:326)
	at java.base/sun.nio.cs.StreamDecoder.read(StreamDecoder.java:178)
	at java.base/java.io.InputStreamReader.read(InputStreamReader.java:185)
	at java.base/java.io.BufferedReader.fill(BufferedReader.java:161)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:326)
	at java.base/java.io.BufferedReader.readLine(BufferedReader.java:392)
	at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:962)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:14861)
```

How could I fix it ,thanks!

**Comment by jernst98** [comment]
Can you check that there is not a corrupt .gz file in the directory with the coordinates for the overlap enrichment?

-Jason

**Comment by Simple53** [comment]
Oh, that was my mistake. The reference files were generated by myself. I checked the COORDS folder and found the truncated '.gz' file:
```
gzip -t *
gzip: CpGIsland.emu3rc.bed.gz: invalid compressed data--format violated
```
Thanks very much for your guidance!

**Comment by Simple53** [comment]
I've got another err:
```
Exception in thread "main" java.lang.IllegalArgumentException: Coordinates in RefSeqExon.emu3rc.bed.gz not assigned to any state. Check if chromosome naming in RefSeqExon.emu3rc.bed.gz match those in the segmentation file.
	at edu.mit.compbio.ChromHMM.StateAnalysis.enrichmentMax(StateAnalysis.java:1189)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:14861)
```
I noticed a previously mentioned issue, but both my CHROMOSIZES and COORDS files do not have a string like "chr", may it cause this err? Thanks.

**Comment by jernst98** [comment]
Yes, the chromosome naming needs to be consistent between what is given for the segmentation/annotation step and the enrichment step. You either need to consistently use or not use 'chr' naming.
