### ISSUE TITLE
Exception in thread "main" java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by El-Castor** [jernst98/ChromHMM#44]
Hi, 

Thanks for your impressive tools! I have used it without error some years ago but using the same conda environnement now it did'nt work, see the error below : 

```bash
Exception in thread "main" java.lang.UnsatisfiedLinkError: /opt/share/FLOCAD/userspace/cpichot/miniconda3/envs/chromHMM/x86_64-conda_cos6-linux-gnu/sysroot/usr/lib/jvm/java-1.7.0-openjdk-1.7.0.131.x86_64/jre/lib/amd64/libnet.so: libgconf-2.so.4: Ne peut ouvrir le fichier d'objet partagé: Aucun fichier ou dossier de ce type
	at java.lang.ClassLoader$NativeLibrary.load(Native Method)
	at java.lang.ClassLoader.loadLibrary1(ClassLoader.java:1968)
	at java.lang.ClassLoader.loadLibrary0(ClassLoader.java:1893)
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1875)
	at java.lang.Runtime.loadLibrary0(Runtime.java:849)
	at java.lang.System.loadLibrary(System.java:1088)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:67)
	at sun.security.action.LoadLibraryAction.run(LoadLibraryAction.java:47)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.InetAddress.<clinit>(InetAddress.java:291)
	at sun.font.FcFontConfiguration.getFcInfoFile(FcFontConfiguration.java:352)
	at sun.font.FcFontConfiguration.readFcInfo(FcFontConfiguration.java:425)
	at sun.font.FcFontConfiguration.init(FcFontConfiguration.java:94)
	at sun.font.FcFontConfiguration.<init>(FcFontConfiguration.java:76)
	at sun.awt.X11FontManager.createFontConfiguration(X11FontManager.java:747)
	at sun.font.SunFontManager$2.run(SunFontManager.java:431)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.SunFontManager.<init>(SunFontManager.java:376)
	at sun.awt.X11FontManager.<init>(X11FontManager.java:32)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:526)
	at java.lang.Class.newInstance(Class.java:383)
	at sun.font.FontManagerFactory$1.run(FontManagerFactory.java:83)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.font.FontManagerFactory.getInstance(FontManagerFactory.java:74)
	at sun.font.SunFontManager.getInstance(SunFontManager.java:250)
	at sun.font.FontDesignMetrics.getMetrics(FontDesignMetrics.java:264)
	at sun.java2d.SunGraphics2D.getFontMetrics(SunGraphics2D.java:819)
	at org.tc33.jheatchart.HeatChart.measureComponents(HeatChart.java:1411)
	at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1301)
	at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1354)
	at edu.mit.compbio.ChromHMM.Util.printImageToSVG(Util.java:140)
	at edu.mit.compbio.ChromHMM.ChromHMM.printEmissionImage(ChromHMM.java:1547)
	at edu.mit.compbio.ChromHMM.ChromHMM.trainParametersParallel(ChromHMM.java:11563)
	at edu.mit.compbio.ChromHMM.ChromHMM.buildModel(ChromHMM.java:1039)
	at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:13867)

```

Interestigly the model in output I have the emmission and transition files : 
see output in console :+1: 
```bash
Using 12 threads for Baum-Welch training
Writing to file /K/FLOCAD/Bioinfo/Workspace/ClementP/DavidL/ATACseq/ATACseq_cytometry_oct2018/machine_learning/building_promoter_states_model/chromoHMM/models_based_on_epigenomeLandscape/test_on_all_chIPseq_data/output_leran_model_leaf_melo_chipMedipData_defaultOption/transitions_8.txt
Writing to file /K/FLOCAD/Bioinfo/Workspace/ClementP/DavidL/ATACseq/ATACseq_cytometry_oct2018/machine_learning/building_promoter_states_model/chromoHMM/models_based_on_epigenomeLandscape/test_on_all_chIPseq_data/output_leran_model_leaf_melo_chipMedipData_defaultOption/emissions_8.txt
```

Do you know how can I fix the java error please to continue the analysis ?

Thanks in advance!

**Comment by jernst98** [comment]
ChromHMM is having problems outputting images based on your local Java configuration. If you don't need the image output you can add the flag '-noimage' which prevents it from trying to output image files.

**Comment by El-Castor** [comment]
Hi, 

Thanks for your quick response, that I didn't understand is that is was working before with this install, I have the image. I have check for the lib that it didn't acces and it exist ... I don't understand the issue. 

Should I have another way to produce the image ? I needed unfortunately ...


thanks jernst98 for your help

**Comment by jernst98** [comment]
If the library exists, there might be some type of path configuration issue on your system.

All the data behind the image ChromHMM outputs are also output in text files, so you can also use those files with standard software for making heatmaps.

**Comment by El-Castor** [comment]
So I have trying with the flag '-noimage' and it's work well. I will try with the administrator to fix the issue later.In parallel I will try using  heatmap software to produce the image. 

Thanks for your help, I keep you in touch for the Java issue

**Comment by El-Castor** [comment]
Hi have a quick question that is not related to this issue, how I can get gene related to clustered chromatin region please?

**Comment by jernst98** [comment]
I am not sure exactly what you mean by related here, but you could use BedTools to relate coordinate sets from the segmentation to existing gene annotations.

**Comment by El-Castor** [comment]
Ok thanks I will try
