### ISSUE TITLE
ConvertGeneTable: Exception in thread "main" java.lang.IllegalArgumentException: invalid strand

### ISSUE THREAD

**Issue by OscarAramburu** [jernst98/ChromHMM#49]
Hi, I have been trying to use the ConvertGeneTable command to generate the ANCHORFILES and COORDS files from my .genepred file, and i get the following error:

`> java -Xmx1500m -jar ChromHMM.jar ConvertGeneTable
 E:/ImmunoMaps_ChromHMM/ASM1334776v1.genePred turbot ASM1334776v1
Exception in thread "main" java.lang.IllegalArgumentException: invalid strand       14322601
        at edu.mit.compbio.ChromHMM.ConvertGeneTable.convertGeneTableToAnnotations(ConvertGeneTable.java:208)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:15233)`

According to the error it looks like for the second row (ENSSMAT00000008045) it skips the value on the third column (-) and takes the value on the fourth (14322601) as the "strand" for that entry. The format of the genePred file is as follows

>head ASM1334776v1.genePred
ENSSMAT00000061270      1       -       51967   54707   52894   54707   2       51967,54230,    53881,54707,    0       ENSSMAG00000030099      cmpl    cmpl    0,0,
ENSSMAT00000008045      1       -       14322601        14331939        14322791        14331939        8       14322601,14323719,14324234,14325124,14327855,14329940,14331566,14331785,14322988,14324074,14324315,14325342,14327992,14330050,14331736,14331939,        0       ENSSMAG00000004910      cmpl    cmpl    1,0,0,1,2,0,1,0,
ENSSMAT00000038001      1       +       9276975 9278241 9276975 9278241 1       9276975,        9278241,        0       ENSSMAG00000022266      incmpl  cmpl    0,
ENSSMAT00000044920      1       +       14333081        14337821        14337821        14337821        2       14333081,14335838,      14333224,14337821,      0       ENSSMAG00000024536      none    none    -1,-1,
ENSSMAT00000020055      1       +       9289166 9293841 9289721 9293225 8       9289166,9289379,9289716,9291523,9291756,9292020,9292573,9292965,        9289287,9289432,9290570,9291653,9291914,9292220,9292752,9293841,        0       ENSSMAG00000012080      cmpl    cmpl    -1,-1,0,0,1,0,2,1,
ENSSMAT00000012406      1       -       27282203        27301256        27285485        27300733        3       27282203,27290895,27298968,     27285808,27291000,27301256,     0      ENSSMAG00000007495       cmpl    cmpl    1,1,0,
ENSSMAT00000020092      1       +       9301215 9308432 9302142 9307959 4       9301215,9305684,9306873,9307197,        9302145,9305907,9307022,9308432,        0       ENSSMAG00000012175      cmpl    cmpl    0,0,1,0,
ENSSMAT00000068326      1       +       27347062        27359181        27347062        27358181        7       27347062,27348950,27350156,27350435,27351651,27352636,27358016, 27347492,27349090,27350321,27350614,27351782,27352809,27359181, 0       ENSSMAG00000032527      cmpl    cmpl    0,1,0,0,2,1,0,
ENSSMAT00000022271      1       +       30600328        30607311        30602844        30607311        7       30600328,30602717,30603532,30603852,30604569,30605878,30607152, 30601158,30603186,30603657,30603949,30604651,30605982,30607311, 0       ENSSMAG00000013466      cmpl    cmpl    -1,0,0,2,0,1,0,
ENSSMAT00000039694      1       +       27360494        27371445        27360494        27371445        5       27360494,27360894,27362245,27363317,27371291,   27360747,27361253,27362292,27363560,27371445,   0       ENSSMAG00000035057      cmpl    cmpl    0,1,0,2,2,

**Comment by jernst98** [comment]
ChromHMM expects the file in the same format as outputted by the UCSC genome table browser, which includes the first column having a bin ID (not actually used by ChromHMM). Also note the first line is assumed to be a header line which is stripped by ChromHMM.

**Comment by OscarAramburu** [comment]
I am using one of the utilities mentioned in the ChromHMM manual (page22) to convert my gtf file (downloaded from ensembl) into the GenePred format, as there is no option to get the file from the UCSC genome table browser for my species (turbot). There is an entry in the UCSC browser (GCF_013347765.1), just not in the table browser
The tool I used was this one
gtfToGenePred (http://hgdownload.soe.ucsc.edu/admin/exe/linux.x86_64.v369/gtfToGenePred)

**Comment by jernst98** [comment]
I think the only difference between the formats is the additional first column and header row. I'll look into adding support for both formats in the next version of ChromHMM and clarify the documentation. In the mean time as a simple work around you should just be able to add a dummy first column and a header line to your current genepred file
