### ISSUE TITLE
Exception in thread "main" java.lang.IllegalArgumentException: . is an invalid strand!

### ISSUE THREAD

**Issue by chrisclarkson** [jernst98/ChromHMM#5]
I have downloaded and unzipped the latest chromhmm version, the 'learn model' test worked on the supplied test data.

Now I have tried to work with my own bed files.
```
less ES-Bruce4/cell-markfile.txt
ES-Bruce4       CTCF    CTCF_ES-Bruce4_ENCFF001YAC.bed.gz
ES-Bruce4       EP300   EP300_ES-Bruce4_ENCFF001YAD.bed.gz
ES-Bruce4       H3K27ac H3K27ac_ES-Bruce4_ENCFF001XWR.bed.gz
ES-Bruce4       H3K27me3        H3K27me3_ES-Bruce4_ENCFF001XWQ.bed.gz
ES-Bruce4       H3K36me3        H3K36me3_ES-Bruce4_ENCFF001XWS.bed.gz
ES-Bruce4       H3K4me1 H3K4me1_ES-Bruce4_ENCFF001XWT.bed.gz
ES-Bruce4       H3K4me3 H3K4me3_ES-Bruce4_ENCFF001XWU.bed.gz
ES-Bruce4       H3K9ac  H3K9ac_ES-Bruce4_ENCFF001XWO.bed.gz
ES-Bruce4       H3K9me3 H3K9me3_ES-Bruce4_ENCFF001XWP.bed.gz
ES-Bruce4       POLR2A  POLR2A_ES-Bruce4_ENCFF001YAE.bed.gz

ls ES-Bruce4/
cell-markfile.txt                      H3K4me1_ES-Bruce4_ENCFF001XWT.bed.gz
CTCF_ES-Bruce4_ENCFF001YAC.bed.gz      H3K4me3_ES-Bruce4_ENCFF001XWU.bed.gz
EP300_ES-Bruce4_ENCFF001YAD.bed.gz     H3K9ac_ES-Bruce4_ENCFF001XWO.bed.gz
H3K27ac_ES-Bruce4_ENCFF001XWR.bed.gz   H3K9me3_ES-Bruce4_ENCFF001XWP.bed.gz
H3K27me3_ES-Bruce4_ENCFF001XWQ.bed.gz  POLR2A_ES-Bruce4_ENCFF001YAE.bed.gz
H3K36me3_ES-Bruce4_ENCFF001XWS.bed.gz  Predictions

java -mx1600M -jar ~/ChromHMM/ChromHMM.jar BinarizeBed ~/ChromHMM/CHROMSIZES/mm9.txt ES-Bruce4 ES-Bruce4/cell-markfile.txt ChromHMM_binary
Exception in thread "main" java.lang.IllegalArgumentException: . is an invalid strand!
    at edu.mit.compbio.ChromHMM.Preprocessing.loadGrid(Preprocessing.java:419)
    at edu.mit.compbio.ChromHMM.Preprocessing.makeBinaryDataFromBed(Preprocessing.java:654)
    at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:5336)


```

The contents of the bed files look as follows:

```
chr1    4132274 4133274 .       18      .       1.83145 -1      -1
chr1    4286878 4287878 .       21      .       2.16857 -1      -1
chr1    4322211 4323211 .       14      .       1.49586 -1      -1
chr1    4335945 4336945 .       15      .       1.52915 -1      -1
chr1    4406497 4407497 .       72      .       7.25079 -1      -1
chr1    4481706 4482706 .       41      .       4.1287  -1      -1
chr1    4506335 4507335 .       31      .       3.14219 -1      -1
chr1    4758160 4759160 .       34      .       3.49081 -1      -1
chr1    4759678 4760678 .       16      .       1.60139 -1      -1
chr1    4904160 4905160 .       24      .       2.43038 -1      -1
```

**Comment by ernstlab** [comment]
The strand should either be a '+' or a '-'. If your reads are unstranded and you want to use the center position for binarization then add the flag '-center'.
