### ISSUE TITLE
NeighborhoodEnrichment error

### ISSUE THREAD

**Issue by katsikora** [jernst98/ChromHMM#60]
Hi,

thanks for this super handy software.

I have some issues with the neighbourhood enrichment function.
I'm running 
```NeighborhoodEnrichment segments.bed TSS0.bed TSS0_neighbourhood```

I'm getting the error:
```
Computing Enrichments...
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 2
        at edu.mit.compbio.ChromHMM.StateAnalysis.neighborhoodMax(StateAnalysis.java:2946)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:14850)
```

ChromHMM 1.25 from bioconda.

Would you be able to advise me as to what might be going wrong?

Thank you very much,
With best regards,

Katarzyna

**Comment by katsikora** [comment]
Perfect, thanks! That fixed it.
