### ISSUE TITLE
Bug: ChromHMM in screen

### ISSUE THREAD

**Issue by freedog8** [jernst98/ChromHMM#9]
when using screen command and then execute ChromHMM in that newly created screen, it use abort with:
Writing to file OUTPUTSAMPLE/transitions_10.txt
Writing to file OUTPUTSAMPLE/emissions_10.txt
Exception in thread "main" java.awt.AWTError: Can't connect to X11 window server using 'localhost:11.0' as the value of the DISPLAY variable.
        at sun.awt.X11GraphicsEnvironment.initDisplay(Native Method)
        at sun.awt.X11GraphicsEnvironment.access$200(X11GraphicsEnvironment.java:65)
        at sun.awt.X11GraphicsEnvironment$1.run(X11GraphicsEnvironment.java:115)
        at java.security.AccessController.doPrivileged(Native Method)
        at sun.awt.X11GraphicsEnvironment.<clinit>(X11GraphicsEnvironment.java:74)
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:264)
        at java.awt.GraphicsEnvironment.createGE(GraphicsEnvironment.java:103)
        at java.awt.GraphicsEnvironment.getLocalGraphicsEnvironment(GraphicsEnvironment.java:82)
        at java.awt.image.BufferedImage.createGraphics(BufferedImage.java:1181)
        at org.tc33.jheatchart.HeatChart.measureComponents(HeatChart.java:1406)
        at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1301)
        at org.tc33.jheatchart.HeatChart.getChartImage(HeatChart.java:1354)
        at edu.mit.compbio.ChromHMM.Util.printImageToSVG(Util.java:140)
        at edu.mit.compbio.ChromHMM.ChromHMM.printEmissionImage(ChromHMM.java:1285)
        at edu.mit.compbio.ChromHMM.ChromHMM.trainParameters(ChromHMM.java:6204)
        at edu.mit.compbio.ChromHMM.ChromHMM.buildModel(ChromHMM.java:885)
        at edu.mit.compbio.ChromHMM.ChromHMM.main(ChromHMM.java:10485)

**Comment by ernstlab** [comment]
See this thread:
https://github.com/jernst98/ChromHMM/issues/1

-Jason
